// <auto-generated>
// Unit tests for MaskRule parser and evaluator using xUnit
// Uses unsafe ushort* to simulate pixel data
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using FlashHSI.Core.Masking;
using Xunit;

namespace FlashHSI.Tests
{
    public class MaskRuleTests
    {
        private unsafe ushort* CreateSpectrum(params ushort[] values)
        {
            // Allocate unmanaged memory for the spectrum
            var ptr = (ushort*)Marshal.AllocHGlobal(values.Length * sizeof(ushort));
            for (int i = 0; i < values.Length; i++)
                ptr[i] = values[i];
            return ptr;
        }

        private unsafe void FreeSpectrum(ushort* ptr)
        {
            Marshal.FreeHGlobal((IntPtr)ptr);
        }

        [Fact]
        public unsafe void SimpleGreaterThanRule_ShouldEvaluateCorrectly()
        {
            var rule = MaskRuleParser.Parse("b0 > 10");
            Assert.NotNull(rule);
            var spectrum = CreateSpectrum(5, 20);
            try
            {
                // b0 = 5, should be false
                Assert.False(rule.Evaluate(spectrum));
                // modify value to satisfy condition
                spectrum[0] = 15;
                Assert.True(rule.Evaluate(spectrum));
            }
            finally
            {
                FreeSpectrum(spectrum);
            }
        }

        [Fact]
        public unsafe void ComplexAndRule_ShouldEvaluateCorrectly()
        {
            var rule = MaskRuleParser.Parse("b0 > 10 & b1 < 5");
            Assert.NotNull(rule);
            var spectrum = CreateSpectrum(12, 3);
            try
            {
                // both conditions true
                Assert.True(rule.Evaluate(spectrum));
                // make second condition false
                spectrum[1] = 6;
                Assert.False(rule.Evaluate(spectrum));
                // make first condition false
                spectrum[0] = 8;
                spectrum[1] = 3;
                Assert.False(rule.Evaluate(spectrum));
            }
            finally
            {
                FreeSpectrum(spectrum);
            }
        }

        [Fact]
        public unsafe void OrAndParenthesesRule_ShouldEvaluateCorrectly()
        {
            var rule = MaskRuleParser.Parse("(b0 > 10 & b1 < 5) | b2 >= 7");
            Assert.NotNull(rule);
            var spectrum = CreateSpectrum(12, 3, 6);
            try
            {
                // first part true, second false -> true
                Assert.True(rule.Evaluate(spectrum));
                // first part false, second false -> false
                spectrum[0] = 8; // b0 <=10
                Assert.False(rule.Evaluate(spectrum));
                // second part true -> true
                spectrum[2] = 7;
                Assert.True(rule.Evaluate(spectrum));
            }
            finally
            {
                FreeSpectrum(spectrum);
            }
        }
    }
}
